version: '3'
services:
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'hula_application'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 33066:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=33066
      - PMA_USER=root
      - PMA_PASSWORD=secret
volumes:
  mysqldata: {}